### ISSUE TITLE
PATH Error using ScanCode as a Scanner on Cygwin

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#1931] opened 2019-11-04 16:11 UTC
When I execute `gradlew cli:run --args="--info scan -f JSON -i <ort_file_path>\ort\analyzer\analyzer-result.json -o <folder_path>\ort\scanner"` I get:

```
> Configure project :
Reckoned version: 0.1.0-beta.0.4184+20191104T155526Z

> Task :cli:run
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-beta.0.4184+20191104T155526Z.
 /   |   \|       _/ |    |    Running 'scan' on Java 12.0.2 and Windows 10 with
/    |    \    |   \ |    |    OS = Windows_NT
\_______  /____|_  / |____|    COMSPEC = C:\WINDOWS\system32\cmd.exe
        \/       \/
More environment variables:
TERM = cygwin
JAVA_HOME = C:\Program Files\Java\jdk-12.0.2
ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk

Using scanner 'ScanCode' with storage 'FileBasedStorage'.
16:55:38.481 [main] INFO  com.here.ort.commands.ScannerCommand - Local file storage has 0 scan results files.
16:55:41.674 [main] INFO  com.here.ort.scanner.LocalScanner - Bootstrapping scanner 'ScanCode' as required version 3.0.2 was not found in PATH.
16:55:41.675 [main] INFO  com.here.ort.scanner.scanners.ScanCode - Downloading ScanCode from https://github.com/nexB/scancode-toolkit/archive/v3.0.2.zip...
16:55:43.077 [main] INFO  com.here.ort.scanner.scanners.ScanCode - Retrieved ScanCode from local cache.
16:57:16.856 [main] INFO  com.here.ort.scanner.scanners.ScanCode - Unpacking '<my_user_path>\AppData\Local\Temp\ort13965838901154634866ScanCode-v3.0.2.zip' to '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2'...
16:57:55.651 [main] INFO  com.here.ort.utils.ProcessCapture - Running '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in '<my_user_path>\Documents\04_oss-review-toolkit\oss-review-toolkit\cli'...
Exception in thread "main" java.io.IOException: Running '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in '<my_user_path>\Documents\04_oss-review-toolkit\oss-review-toolkit\cli' failed with exit code 1:
  The script chardetect.exe is installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts futurize.exe and pasteurize.exe are installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pygmentize.exe is installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts csv2rdf.exe, rdf2dot.exe, rdfgraphisomorphism.exe, rdfpipe.exe and rdfs2dot.exe are installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script spdx-tv2rdf.exe is installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script calc-prorate.exe is installed in '<my_user_path>\AppData\Local\Temp\ort16223165339819254102ScanCode-3.0.2\scancode-toolkit-3.0.2\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

        at com.here.ort.utils.ProcessCapture.requireSuccess(ProcessCapture.kt:145)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:90)
        at com.here.ort.scanner.scanners.ScanCode$getVersion$tool$1.run(ScanCode.kt:245)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:99)
        at com.here.ort.scanner.scanners.ScanCode$getVersion$tool$1.getVersion(ScanCode.kt:245)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:97)
        at com.here.ort.scanner.scanners.ScanCode.getVersion(ScanCode.kt:249)
        at com.here.ort.scanner.LocalScanner$scannerDir$2.invoke(LocalScanner.kt:117)
        at com.here.ort.scanner.LocalScanner$scannerDir$2.invoke(LocalScanner.kt:74)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.here.ort.scanner.LocalScanner.getScannerDir(LocalScanner.kt)
        at com.here.ort.scanner.LocalScanner.getVersion$default(LocalScanner.kt:148)
        at com.here.ort.scanner.LocalScanner.getDetails(LocalScanner.kt:165)
        at com.here.ort.scanner.LocalScanner.scanPackages$suspendImpl(LocalScanner.kt:169)
        at com.here.ort.scanner.LocalScanner.scanPackages(LocalScanner.kt)
        at com.here.ort.scanner.Scanner$scanOrtResult$results$1.invokeSuspend(Scanner.kt:135)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.here.ort.scanner.Scanner.scanOrtResult(Scanner.kt:135)
        at com.here.ort.commands.ScannerCommand.runCommand(ScannerCommand.kt:192)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:55)
        at com.here.ort.Main.runCommand(Main.kt:139)
        at com.here.ort.CommandWithHelp.run(CommandWithHelp.kt:55)
        at com.here.ort.Main.run(Main.kt:122)
        at com.here.ort.Main.main(Main.kt:99)

> Task :cli:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:run'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 40s
44 actionable tasks: 21 executed, 23 up-to-date
```
I hope I don't need to further downgrade my OpenJDK version :-), by the way there is a newer available version of the `scancode-toolkit` (v3.1.1).

**Comment by sschuberth** [comment] 2019-11-04 18:43
> by the way there is a newer available version of the `scancode-toolkit` (v3.1.1).

Yes, but that's just a pre-release / "[A release candidate 2 for 3.1.x](https://github.com/nexB/scancode-toolkit/releases/tag/v3.1.1)".

**Comment by sschuberth** [comment] 2019-11-05 07:38
Actually, it just occurred to me that the Python version you're using might also be a Cygwin Python, is that correct? If that's the case, *that* might actually be the root cause. I highly recommend to use a [native Python](https://www.python.org/ftp/python/2.7.17/python-2.7.17.amd64.msi) version and run ORT under "pure" Windows. or under real Linux, but not under an emulation layer like Cygwin.

**Comment by CleanHit** [comment] 2019-11-05 07:45
This is weird. My Python 2.x and 3.x versions came from the official Python web page.

**Comment by sschuberth** [comment] 2019-11-05 07:50
Well, then regarding Python all *might* be fine, except if you *also* have the Python Cygwin package installed, and run from a Cygwin shell.

To rule out any Cygwin-related issues you should run from a pure native Windows `cmd` command prompt, and verify that the Python in your PATH is a native Windows version of Python (e.g. by running `where python.exe` and ensuring that the reported path(s) do not point to your Cygwin installation directory).

**Comment by CleanHit** [comment] 2019-11-05 09:28
> where python.exe

Returned the usual install paths when installing Python using the official Python web page.
> 
> 
> > TERM = cygwin
> 
> I see you're running on Cygwin, which might do some path mangling. Do you get the same error when running the same command from a `cmd` prompt?

This is also strange because I don’t have Cygwin or any Cygwin packages installed. When I execute the command in Cmder tool then this `TERM` is being shown but when I execute it in the native window `cmd` Then the `TERM` is not showing at all.

Nevertheless, the error message is still there when using native `cmd`

**Comment by sschuberth** [comment] 2019-11-05 10:00
@pombredanne, as this seems to be a Python issue, do you have any idea what's goiong on?

**Comment by pombredanne** [comment] 2019-11-05 18:08
@CleanHit @sschuberth Not sure what is going on, but a simple way to rule out issues would be to download the same version (e.g. 3.0.2) and run something to see if there is an issue there too.

@CleanHit That would mean fetching https://github.com/nexB/scancode-toolkit/releases/tag/v3.0.2 
then extracting and running a simple `scancode --version` then `scancode --verbose --info --json-pp - samples` and report the output here.

**Comment by CleanHit** [comment] 2019-11-05 19:53
@sschuberth @pombredanne I can check it only next week Wednesday.

**Comment by CleanHit** [comment] 2019-11-12 10:37
@pombredanne @sschuberth I'm suspecting that the issue is my Python 2.7 x64 version. But when I install the x86 version of Python 2.7.x (MSI) I get the missing `python27.dll` error.

**Comment by sschuberth** [comment] 2019-11-12 10:50
> I'm suspecting that the issue is my Python 2.7 x64 version.

Correct, I recall having problems with 64-bit Python, too, and it's also documented at https://github.com/nexB/scancode-toolkit#installation to use 32-bit Python.

> But when I install the x86 version of Python 2.7.x (MSI) I get the missing `python27.dll` error.

Hm, that actually worked for me just fine... when does the error occur, and what's the exact message?

**Comment by CleanHit** [comment] 2019-11-12 11:28
> > But when I install the x86 version of Python 2.7.x (MSI) I get the missing `python27.dll` error.
> 
> Hm, that actually worked for me just fine... when does the error occur, and what's the exact message?

Well the missing `python.dll` error is gone after deleting the folder and cloning the repository again, First I've cloned the `master` branch, executed `scancode --version` and everything works fine. When I checkout the 3.0.2 tag and execute `scancode --version` I get

```

(scancode-toolkit) λ scancode --version
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
cannot import name get_package_instance
========================================================================
Traceback (most recent call last):
  File "c:\scancode\scancode-toolkit\Scripts\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "c:\scancode\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\scancode\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\scancode\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\scancode\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\scancode\scancode-toolkit\src\scancode\cli.py", line 214, in <module>
    raise e
ImportError: cannot import name get_package_instance
```
even when checking out the `master` branch again. Maybe I need to reconfigure it again after checking out a different version. I didn't find such command using `scancode -h` when it was first working by pooling the `master` branch at first.

**Comment by sschuberth** [comment] 2019-11-12 11:46
> Maybe I need to reconfigure it again after checking out a different version.

Yes, you do! Please just run `configure --clean` after switching versions.

**Comment by CleanHit** [comment] 2019-11-12 12:20
I did it and it worked, now I can use the v3.0.2. running `scancode --verbose --info --json-pp - samples` executed without problems:

```
Scanning done.
Summary:        info with 1 process(es)
Errors count:   0
Scan Speed:     10.67 files/sec. 366.71 KB/sec.
Initial counts: 44 resource(s): 33 file(s) and 11 directorie(s)
Final counts:   44 resource(s): 33 file(s) and 11 directorie(s) for 1.11 MB
Timings:
  scan_start: 2019-11-12T115937.078000
  scan_end:   2019-11-12T115940.238000
  scan: 3.09s
  output:json-pp: 0.42s
  output: 0.42s
  total: 3.58s
Removing temporary files...done.
```

But executing `.\ort.bat --info scan -f JSON -i <ort_file_path>\ort\analyzer\analyzer-result.json -o <folder_path>\ort\scanner` in my project results in a different error than I've posted at the begining of the post. Now I get:

```
12:53:34.364 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running '<my_user_path>\AppData\Local\Temp\ort13167018435145380138ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --processes 7 <folder_path>\ort\scanner\downloads\Maven\androidx.annotation\annotation\1.0.0 --json-pp <folder_path>\ort\scanner\native-scan-results\Maven\androidx.annotation\annotation\1.0.0\scan-results_ScanCode.json' in 'C:\oss-review-toolkit\cli\build\install\ort\bin'...
Exception in thread "main" java.lang.NullPointerException
        at com.here.ort.scanner.scanners.ScanCode.getFileCount(ScanCode.kt:359)
        at com.here.ort.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:366)
        at com.here.ort.scanner.scanners.ScanCode.scanPath(ScanCode.kt:327)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:333)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        Suppressed: java.lang.NullPointerException
                ... 11 more
```

**Comment by sschuberth** [comment] 2019-11-12 12:38
Can you share the raw scan result (the JSON file) from that scan, eventually with all file results stripped? ORT seems to think this is a scan result from ScanCode <= 2.9.7 and handles it accordingly.

**Comment by sschuberth** [comment] 2019-11-12 12:41
In particular, there should be a header with a `files_count` field similar to this one:

```
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.0.2",
      "options": {
        "input": "/home/getting-started/mime-types",
        "--copyright": true,
        "--ignore": [
          "*.ort.yml",
          "HERE_NOTICE",
          "META-INF/DEPENDENCIES"
        ],
        "--info": true,
        "--json-pp": "/home/getting-started/out/scanner/native-scan-results/mime-types_ScanCode.json",
        "--license": true,
        "--processes": "3",
        "--strip-root": true,
        "--timeout": "300.0"
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2019-08-13T074443.361209",
      "end_timestamp": "2019-08-13T074524.131834",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 10
      }
    }
  ],
```

**Comment by CleanHit** [comment] 2019-11-12 13:04
The scan process doesn't end successfully so no JSON file gets generated. I have only the **download** and **native-scan-results** folders in my `<folder_path>\ort\scanner\`.

**Comment by sschuberth** [comment] 2019-11-12 13:14
Ok, that particular issue should be fixed by https://github.com/heremaps/oss-review-toolkit/pull/1952.

**Comment by CleanHit** [comment] 2019-11-12 13:51
> In particular, there should be a header with a `files_count` field similar to this one:

Here is my header of the failed scan:
```

"headers":[{
	"tool_name":"scancode-toolkit",
	"tool_version":"3.0.2",
	"options":{
		"input":"<folder_path>\\ort\\scanner\\downloads\\Maven\\androidx.appcompat\\appcompat-resources\\1.1.0",
		"--copyright":true,
		"--ignore":[
			"*.ort.yml",
			"HERE_NOTICE",
			"META-INF/DEPENDENCIES"
			],
			"--info":true,
			"--json-pp":"<folder_path>\\ort\scanner\\native-scan-results\\Maven\\androidx.appcompat\\appcompat-resources\\1.1.0\\scan-results_ScanCode.json","--license":true,
			"--processes":"7",
			"--strip-root":true,
			"--timeout":"300.0"
		},
		"notice":"Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
		"start_timestamp":"2019-11-12T114948.376000",
		"end_timestamp":"2019-11-12T115129.982000",
		"message":null,
		"errors":[],
		"extra_data":{
			"files_count":13
		}
	}
],
```

**Comment by sschuberth** [comment] 2019-11-12 14:45
Hmm, are you sure this is from the *failed* scan, as it has `"errors":[]` (no errors) and `"files_count":13` (non-zero files count)?

**Comment by CleanHit** [comment] 2019-11-12 14:51
> Hmm, are you sure this is from the _failed_ scan, as it has `"errors":[]` (no errors) and `"files_count":13` (non-zero files count)?

It's from the file loceated in `<my_result_location>\ort\scanner\native-scan-results\Maven\androidx.appcompat\appcompat-resources\1.1.0\scan-results_ScanCode.json`

**Comment by sschuberth** [comment] 2019-11-12 14:53
Unfortunately, that does not tell me anything in this case. To me it looks like the scan succeeded. What makes you believe it failed?

**Comment by CleanHit** [comment] 2019-11-12 15:09
> 
> 
> Unfortunately, that does not tell me anything in this case. To me it looks like the scan succeeded. What makes you believe it failed?

I see this at the end but if this is how the command execution should end then the scan succeeded.

```
Exception in thread "main" java.lang.NullPointerException
        at com.here.ort.scanner.scanners.ScanCode.getFileCount(ScanCode.kt:359)
        at com.here.ort.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:366)
        at com.here.ort.scanner.scanners.ScanCode.scanPath(ScanCode.kt:327)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:333)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        Suppressed: java.lang.NullPointerException
                ... 11 more
```

**Comment by sschuberth** [comment] 2019-11-12 15:50
Please try again with current *master*. You should not see this `NullPointerException` anymore.

**Comment by CleanHit** [comment] 2019-11-13 11:56
I've pulled the latest `master` branch updates and this exception is gone. The runtime of the scan took about 1 hour  and +/- 15 minutes, after that it exited with this exception.

```
11:45:20.668 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Could not read scan results for 'Maven:cglib:cglib-nodep:3.2.9' from path 'Maven/cglib/cglib-nodep/3.2.9/scan-results.yml': FileNotFoundException: <my_user_path>\.ort\scanner\results\Maven\cglib\cglib-nodep\3.2.9\scan-results.yml (Das System kann den angegebenen Pfad nicht finden)
11:45:20.691 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'Maven:cglib:cglib-nodep:3.2.9' at path 'Maven/cglib/cglib-nodep/3.2.9/scan-results.yml'.
11:45:20.692 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning Maven:cglib:cglib-nodep:3.2.9 (49/256).
Exception in thread "main" java.io.IOException: Cannot run program "cvs": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:86)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:29)
        at com.here.ort.utils.ProcessCapture.<init>(ProcessCapture.kt:33)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:90)
        at com.here.ort.downloader.vcs.Cvs.run(Cvs.kt:41)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:99)
        at com.here.ort.downloader.vcs.Cvs.getVersion(Cvs.kt:41)
        at com.here.ort.utils.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:97)
        at com.here.ort.downloader.vcs.Cvs.getVersion(Cvs.kt:50)
        at com.here.ort.downloader.vcs.Cvs$download$1.invoke(Cvs.kt:168)
        at com.here.ort.downloader.vcs.Cvs$download$1.invoke(Cvs.kt:41)
        at org.apache.logging.log4j.kotlin.SuppliersKt$asLog4jSupplier$1.get(Suppliers.kt:21)
        at org.apache.logging.log4j.util.LambdaUtil.getMessage(LambdaUtil.java:91)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1997)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1860)
        at org.apache.logging.log4j.kotlin.KotlinLogger.info(KotlinLogger.kt:355)
        at com.here.ort.downloader.vcs.Cvs.download(Cvs.kt:168)
        at com.here.ort.downloader.VersionControlSystem.download$default(VersionControlSystem.kt:218)
        at com.here.ort.downloader.Downloader.downloadFromVcs(Downloader.kt:238)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:144)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:300)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:74)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 30 **more**
```

**Comment by sschuberth** [comment] 2019-11-13 12:02
> Cannot run program "cvs": CreateProcess error=2, Das System kann die angegebene Datei nicht finden

Like the error message indicates, you're lacking the `cvs` command line tool. This needs to be installed if the source code of any of your dependencies is hosted in CVS, so ORT can use it to check out the source code in order to scan it.

**Comment by CleanHit** [comment] 2019-11-13 14:22
Ok now it has a problem with not finding `svn`, I'll install the `tortoiseSVN` and run it again.

**Comment by CleanHit** [comment] 2019-11-14 11:24
It is running the scan for 3 hours now and is stuck in the last 1.5 hours on one place.

**Comment by sschuberth** [comment] 2019-11-14 11:28
Depending on the size of the source code of the current package that might be ok. We've seen scan times > 10 hours in extreme cases.

**Comment by CleanHit** [comment] 2019-11-14 11:54
Ok, but I don’t see any resource (CPU, RAM) usage.

**Comment by CleanHit** [comment] 2019-11-14 13:35
> 
> 
> Depending on the size of the source code of the current package that might be ok. We've seen scan times > 10 hours in extreme cases.

Can I restrict the depth of the scan?

**Comment by sschuberth** [comment] 2019-11-14 13:39
Not the depth (in terms of the transitivity level), but the [scopes](https://github.com/heremaps/oss-review-toolkit/blob/6747eae1f884eb611fcb6b1b4372cdc4aace0b3d/cli/src/main/kotlin/commands/ScannerCommand.kt#L79).

**Comment by CleanHit** [comment] 2019-11-14 14:27
> Not the depth (in terms of the transitivity level), but the [scopes](https://github.com/heremaps/oss-review-toolkit/blob/6747eae1f884eb611fcb6b1b4372cdc4aace0b3d/cli/src/main/kotlin/commands/ScannerCommand.kt#L79).

Since I'm only interested in the dependencies and their license adding `--scopes dependencies` should do the trick, right?

**Comment by sschuberth** [comment] 2019-11-14 14:32
Probably not. What needs to get passed to `--scopes` is a package-manager-specific name of the scope of dependencies you want to scan. At the example of Maven, `--scope compile` would only scan the source code of "compile dependencies", but not e.g. of "test dependencies".

Confusingly enough, some package managers (e.g. NPM) call their "compile dependencies" just "dependencies".

TL;DL: The argument to `--scopes` is the literal name of a dependency scope, not an abstract term of *what* to scan.

**Comment by sschuberth** [comment] 2019-11-14 14:36
Thinking about it, IIUC what you want is (in ORT-speak) to skip the scan of the project source code, and only scan the source code of all dependency packages. WHich is somehting that is currently not supported, but which could probably be easily added as part of the work in [my branch to specify a different scanner for projects](https://github.com/heremaps/oss-review-toolkit/tree/separate-project-scanner): You could simply set that scanner to `none` then.

**Comment by CleanHit** [comment] 2019-11-14 15:14
> You could simply set that scanner to `none` then.

Without any scope defined or do I need to set the scope flag to something?

**Comment by sschuberth** [comment] 2019-11-14 15:20
*If* that feature was implemented (it is not currently, also not in my branch) then you would only pass `--project-scanner=none` but no `--scopes` argument at all.

**Comment by CleanHit** [comment] 2019-11-14 15:25
I've tried building the `separate-project-scanner` branch with `.\gradlew.bat installDist` and got:
```
λ .\gradlew.bat installDist
Configuration on demand is an incubating feature.

> Configure project :
Reckoned version: 0.1.0-beta.0.3879+20191114T152133Z

> Task :scanner:compileKotlin FAILED
e: C:\oss-review-toolkit\scanner\src\main\kotlin\Scanner.kt: (106, 41): Cannot access 'scanPackages': it is protected in 'Scanner'
e: C:\oss-review-toolkit\scanner\src\main\kotlin\Scanner.kt: (133, 68): Unresolved reference: config

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scanner:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
32 actionable tasks: 14 executed, 18 up-to-date
```
But as you already said, what I actually want is not yet implemented anyway.

**Comment by sschuberth** [comment] 2019-11-14 15:26
Yeah, currently the branch does not not even build, I'm aware of that.

**Comment by CleanHit** [comment] 2019-11-15 08:32
I left the scanner to work for 14 hours and it is stuck for about 12.5 hours on the same place.
```
17:41:39.441 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Using processed VcsInfo(type=Git, url=ssh://git@github.com/cbeust/jcommander.git, revision=, resolvedRevision=null, path=). Original was VcsInfo(type=Git, url=git@github.com:cbeust/jcommander.git, revision=, resolvedRevision=null, path=).
17:41:39.442 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
17:41:39.466 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in 'C:\oss-review-toolkit\cli\build\install\ort\bin'...
17:41:39.568 [ScanCode-1] INFO  com.here.ort.downloader.VersionControlSystem - Using Git version 2.24.0.windows.2.
17:41:39.590 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git init' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:39.736 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote add origin ssh://git@github.com/cbeust/jcommander.git' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:39.871 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in 'C:\oss-review-toolkit\cli\build\install\ort\bin'...
17:41:39.991 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git config protocol.version 2' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:40.124 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git config core.longpaths true' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:40.258 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git status -sb --porcelain=v2' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:40.395 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote show -n' in 'C:<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
17:41:40.523 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git -c credential.helper= -c core.askpass=echo ls-remote --refs origin refs/tags/*' in '<scanner_output_path>\Android_ort\scanner3\downloads\Maven\com.beust\jcommander\1.48'...
```

It's maybe related to the fact that I have a general problem using `git clone ssh://git@.....` in Windows at the moment, using `git clone https://github.com/cbeust/jcommander.git` worked fine.

**Comment by sschuberth** [comment] 2020-01-17 16:18
@CleanHit, I believe there's nothing left to do here WRT the original issue, so I'm closing this. I haven't had time to finish work on [my branch to specify a different scanner for projects](https://github.com/heremaps/oss-review-toolkit/tree/separate-project-scanner), but strictly speaking that's unrelated to the original issue.

**Closed by sschuberth** 2020-01-17 16:18 UTC
Labels: needs info, scanner
