### ISSUE TITLE
[docker] failed on windows

### ISSUE THREAD

**Issue by fb33** [heremaps/oss-review-toolkit#2084] opened 2019-12-31 10:54 UTC
Hi,

I try to use ORT with docker on windows ...
I run "docker/run.sh xxx" on git bash and I get this error of path (with `;C` at the end): 
```
$ docker/run.sh "-v /c/workspace/POCs/MOB_ORT/my-gateway-web:/project" analyze -i /project/server -o /project/ort/analyzer-server
cat: /c/workspace/POCs/MOB_ORT/docker/oss-review-toolkit/model/src/main/resources/VERSION: No such file or directory
Building ORT...
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM frolvlad/alpine-java:jdk8-slim
 ---> 666b9799aa2a
Step 2/2 : RUN apk add --no-cache libstdc++
 ---> Using cache
 ---> c3f453a829ce
Successfully built c3f453a829ce
Successfully tagged ort-build:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
No Gradle daemons are running.
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Program Files/Git/etc/group;C"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
Failed to build ORT.
```

I go on my test with setting an env var :  `export MSYS_NO_PATHCONV=1`
(maybe an note in the readme will be appreciate by windows users :-) ) 
after this, the path error is gone, but the build failed : 
```
$ docker/run.sh "-v /c/workspace/POCs/MOB_ORT/my-gateway-web:/project" analyze -i /project/server -o /project/ort/analyzer-server
cat: /c/workspace/POCs/MOB_ORT/docker/oss-review-toolkit/model/src/main/resources/VERSION: No such file or directory
Building ORT...
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM frolvlad/alpine-java:jdk8-slim
 ---> 666b9799aa2a
Step 2/2 : RUN apk add --no-cache libstdc++
 ---> Using cache
 ---> c3f453a829ce
Successfully built c3f453a829ce
Successfully tagged ort-build:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
No Gradle daemons are running.
': No such file or directory
Failed to build ORT.
```
any idea ?

Regards

**Comment by sschuberth** [comment] 2019-12-31 11:00
Just FYI, running our images with Docker for Windows is totally untested, and I highly recommend *against* using them on Windows. That's mostly we do some very [Linux-specific tricks](https://github.com/heremaps/oss-review-toolkit/blob/2060060f556ea1d40634f7fa67615d2813eacb5d/docker/lib#L34).

That said, I'm working on a new multi-stage Dockerfile in the [docker-stuff](https://github.com/heremaps/oss-review-toolkit/tree/docker-stuff) branch. You might have more luck running that one on Windows, but it's not ready yet. I plan to finish it early next year.

**Comment by fb33** [comment] 2019-12-31 12:22
> Just FYI, running our images with Docker for Windows is totally untested, and I highly recommend _against_ using them on Windows. That's mostly because we do some very [Linux-specific tricks](https://github.com/heremaps/oss-review-toolkit/blob/2060060f556ea1d40634f7fa67615d2813eacb5d/docker/lib#L34).

Ok, got it !

> That said, I'm working on a new multi-stage Dockerfile in the [docker-stuff](https://github.com/heremaps/oss-review-toolkit/tree/docker-stuff) branch. You might have more luck running that one on Windows, but it's not ready yet. I plan to finish it early next year.

I'll test with that branch.
Thanks

**Comment by fb33** [comment] 2020-01-16 12:19
Hi, I ve just done the test. It fails.
```
PS C:\workspace\POCs\MOB_ORT\oss-review-toolkit> docker build -t ort:docker-stuff .
Sending build context to Docker daemon  15.43MB
Step 1/13 : FROM frolvlad/alpine-java:jdk8-slim AS build
 ---> 666b9799aa2a
Step 2/13 : COPY . /usr/local/src/ort
 ---> 62afa0bc8b70
Step 3/13 : WORKDIR /usr/local/src/ort
 ---> Running in fe351f8e2d8e
Removing intermediate container fe351f8e2d8e
 ---> ad619798532e
Step 4/13 : RUN apk add --no-cache     libstdc++     ca-certificates coreutils openssl &&     scripts/import_proxy_certs.sh
 ---> Running in 09ebb770392c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20190108-r0)
(2/6) Installing libattr (2.4.47-r7)
(3/6) Installing libacl (2.2.52-r5)
(4/6) Installing coreutils (8.30-r0)
(5/6) Installing libstdc++ (8.3.0-r0)
(6/6) Installing openssl (1.1.1d-r2)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
Executing glibc-bin-2.29-r0.trigger
OK: 16 MiB in 23 packages
: not foundort_proxy_certs.sh: line 19:
scripts/import_proxy_certs.sh: line 45: syntax error: unexpected word (expecting "do")
The command '/bin/sh -c apk add --no-cache     libstdc++     ca-certificates coreutils openssl &&     scripts/import_proxy_certs.sh' returned a non-zero code: 2```

**Comment by sschuberth** [comment] 2020-01-16 16:05
Interesting. I assume you have the `https_proxy` environment variable set? Can you share its value?

**Comment by fb33** [comment] 2020-01-17 07:23
Hi, I ve no environment variable set for proxy, no `http_proxy `or `https_proxy`

**Comment by sschuberth** [comment] 2020-01-17 09:17
Hmm, odd. I've made some minor changes and merged the new Docker file to `master` now. Could you please try again? However, if the issue still appears, I'd need your help in debugging this as I cannot reproduce the issue on my Windows machine.

**Comment by fb33** [comment] 2020-01-17 10:15
I found the problem for `scripts/import_proxy_certs.sh: line 45: syntax error: unexpected word (expecting "do")`
I was a problem of eol ! I change crlf to lf for the script file used and gradlew.
I think you can add these lines in `.gitattributes`

```
gradlew   		                        text eol=lf
scripts/*.sh		                        text eol=lf
```

I go on the test

**Comment by sschuberth** [comment] 2020-01-17 10:45
Good finding, thanks. Addressed in https://github.com/heremaps/oss-review-toolkit/pull/2127.

**Comment by sschuberth** [comment] 2020-01-17 12:56
The `.gitattributes` fix is in `master` now. Could you please test one more time and eventually close this issue if it's resolved for you?

**Comment by fb33** [comment] 2020-01-17 13:42
I test with `master `but I ve got this : 
```
env: ‘sh\r’: No such file or directory
The command '/bin/sh -c scripts/set_gradle_proxy.sh &&     ./gradlew --no-daemon :cli:distTar' returned a non-zero code: 127
```

It might be `**/*.sh` rather than `*.sh`  in .gitattributes ?

**Comment by fb33** [comment] 2020-01-17 14:17
It works well when I change eol into `LF ` for the `gradlew `file

**Comment by sschuberth** [comment] 2020-01-17 14:55
Hmm, `git check-attr -a scripts/import_proxy_certs.sh` and `git check-attr -a gradlew` both show `eol: lf` for me, so I believe the matching works. Have you tried deleting an re-checkout-ing these files to ensure Git rewrites them?

**Comment by fb33** [comment] 2020-01-17 15:44
It's OK after deleting end re-checkout  👍 

Thanks

One more thing with Docker, does the ort execution in container are stateless ? 
I mean, does ORT write some files in the container that are re-used between steps of the whole process (analyze, scan, evaluate ...) ? or does the configurable output directory is enough ?

**Comment by sschuberth** [comment] 2020-01-17 15:54
ORT writes some caching data to the user's home directory (as determined by Java's `home.user` property, or OS-specific environment variables as a [fallback](https://github.com/heremaps/oss-review-toolkit/blob/61d97391973567187bd8d4e4c9afecb45c419a74/cli/src/main/kotlin/OrtMain.kt#L109-L129)) inside the `.ort` sub-directory. However these files are lost if you don't keep the container around. So to keep these files and also to pass data from step to the other, you'd need to set the `HOME` or `ORT_USER_HOME` environment variables and use volume mounts, similar to like the new [Jenkinsfile](https://github.com/heremaps/oss-review-toolkit/blob/master/Jenkinsfile) does it.

**Comment by fb33** [comment] 2020-01-17 15:57
Ok thanks for these informations

**Comment by sschuberth** [comment] 2020-01-17 16:02
So, good to close this issue?

**Closed** 2020-01-17 16:09 UTC
Labels: docker
